AGATE-6 Review and Update Docker Images are pushed to quay.io from Ba…
Activiti/activiti-cloud-gateway pull request #16
Opened 2018-01-26 18:32 UTC by jottley

…mboo

Add scripts and property file for building docker image and pushing to quay.io

2018-01-29 07:43 UTC, gavincornwell approved these changes

2018-01-29 08:47 UTC, sergiuv2020 approved these changes

2018-01-29 08:50 UTC, sergiuv2020 requested changes
The Readme needs changing so that the badges point to the correct Travis build, CLA needs updating, Also for the badges to be displayed correctly in Dockerhub there must be only one space between them, no line breaks.

2018-01-30 03:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Alfresco/alfresco-api-gateway?pullRequest=16) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Alfresco/alfresco-api-gateway?pullRequest=16) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Alfresco/alfresco-api-gateway?pullRequest=16) it.</sub>

2018-01-30 09:05 UTC, nicdoye approved these changes

2018-01-30 15:23 UTC, sergiuv2020 approved these changes

2018-01-30 15:28 UTC, merged